apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-demoapp-deployment
  labels:
    app: simple-demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-demoapp
  template:
    metadata:
      labels:
        app: simple-demoapp
    spec:
      containers:
        - name: simple-demoapp-container
          image: simple-demoapp
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: async-profiler
              mountPath: /async-profiler/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: async-profiler
          hostPath:
            path: /Users/d.shurkaev/Desktop/Research/simple-demo/async-profiler
            type: DirectoryOrCreate